services:
  - type: web
    name: my-python-app
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: ENV_FILE
        value: ".env"  # Set this if you need to load environment variables from the .env file
